### ISSUE TITLE
settings.local.php vs settings.dev.php

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/drupal-integrations#3]
We have code in `settings.php` to include `settings.local.php` if present. It also includes `settings.ts.php`.

`settings.ts.php` then has code to include `settings.dev.php` if present.

What is the intended difference between "settings.dev.php" and "settings.local.php"? Should we consider consolidating and only using one of these?

If so, is it "settings.local.php" because that's what Drupal wants us to use?

If so, should we just remove the include of "settings.dev.php" from settings.ts.php?

**Comment by mariacha** [comment]
I think they serve different purposes still.

In our typical drupal setup, settings.dev.php gets committed -- it's shared code between all the devs. Meanwhile settings.local.php is never committed, and gives people a place to define things that are truly only relevant to their local site. I've used it for things like overriding the migration source database, or setting the email address for reroute-email to mine.

That being said, it looks like we don't have a settings.dev.php file at all in the build right now (I don't have one on [ccal](https://github.com/thinkshout/ccal/tree/main/web/sites/default), I'm seeing) -- is that what you're finding too? We can pull it over from here: https://github.com/thinkshout/drupal-project/blob/8.x-pantheon/web/sites/default/settings.dev.php and then just set it as one of those files that is only pulled the first time, so that people can customize it per-repo and get that committed.
